### ISSUE TITLE
Learning Materials Delete Box (Trash Can) is Out Of Alignment

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1147] opened 2015-11-20 19:41 UTC
see screen shot below ...

![image](https://cloud.githubusercontent.com/assets/7493331/11309930/a53c5ea0-8f7b-11e5-9c9c-da5b39d891f1.png)

**Comment by jrjohnson** [comment] 2016-10-11 18:45
Duplicate of #1118

**Closed by jrjohnson** 2016-10-11 18:45 UTC
Labels: duplicate
