### ISSUE TITLE
apply one pattern to all faculty search areas/lists

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#614] opened 2015-05-22 14:51 UTC
right now we have multiple patterns for faculty search: the course director list, the program director / offering instructor list, and the ILM offering manager. We need One Pattern To Rule Them All (or if you prefer Highlander, There Can Be Only One).

Part 2: we have multiple ways of displaying the selected names once done: badges in the course director list, name + "X" control in offerings and programs, and name + "X" control in ILM while managing and name only in ILM after save. We need a single listing pattern for faculty names across the board.

**Comment by jrjohnson** [comment] 2015-05-22 17:27
I think this is a duplicate of #545

**Closed by jrjohnson** 2015-05-22 17:27 UTC
Labels: duplicate
