### ISSUE TITLE
Courses and Sessions >> Edit Start Date >> Calendar Icon Does Not Do Anything

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#372] opened 2015-03-23 22:08 UTC
![calendar](https://cloud.githubusercontent.com/assets/7493331/6791699/5b16406e-d16e-11e4-96e6-a23771f85149.JPG)

This may another pending pull request thing and if so, I apologize.

**Comment by jenzweben** [comment] 2015-03-23 22:14
Duplicate of #311

**Closed by jenzweben** 2015-03-23 22:14 UTC
