### ISSUE TITLE
Parent Objective - Fix Font

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#428] opened 2015-04-06 21:01 UTC
Right now it is Cambria and Century Schoolbook in some cases - should be Helvetica and line spacing should be regular not double.  I can see that objectives.js  contains styles...

![screen shot 2015-04-06 at 1 59 45 pm](https://cloud.githubusercontent.com/assets/5023894/7012326/50c2f1d2-dc65-11e4-8296-57dd1252daff.png)

**Comment by jrjohnson** [comment] 2015-04-19 00:54
I'm guessing this is due to formatting which the user included when saving the objective title.  
@saschaben - I believe we want to show formatted HTML here and not plain text, is that correct?  If so then this should be closed as expected behavior.

**Comment by saschaben** [comment] 2015-04-19 00:57
@jrjohnson yes, this is user-induced cut&paste cruft. closing. Of course, it would be nice if SkyNet would take care of this one as well....

**Comment by jenzweben** [comment] 2015-04-27 23:35
can we not use something like this http://stackoverflow.com/questions/6899659/remove-formatting-from-a-contenteditable-div to fix that issue?

**Comment by saschaben** [comment] 2015-04-27 23:43
@jenzweben the problem here is that we don't want to remove ALL formatting: objectives frequently will have necessary formatting added in the db -- lists, bullets, etc. The problem here is that the junk formatting has gotten in from a cut&paste ction from Word, including styling. We can strip it completely in the view -- which could cause trouble with content being understood -- or we can try to get users to clean up entries by providing more effective editing tools for objectives...but there isn't a simple answer. we should continue to knock this around, as it is definitely an issue.

**Comment by jrjohnson** [comment] 2015-05-19 07:45
Some of this is reflected in #458 - that is as far as we are going to get with this.  Removing or ignoring a specific attribute (like font-face) and keeping a formatted list is too complicated.

**Closed by jrjohnson** 2015-05-19 07:45 UTC
Labels: enhancement, ready
