### ISSUE TITLE
Language selections are being duplicated

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#3124] opened 2017-07-31 19:09 UTC
the language selector is doubling up each language option:

![langdupes](https://user-images.githubusercontent.com/1753431/28793786-07046d76-75e9-11e7-9925-86cbcc64196d.png)

**Comment by dartajax** [comment] 2017-07-31 20:01
Duplicate of #3098

**Comment by dartajax** [comment] 2017-07-31 20:01
Refer to #3098

**Closed by dartajax** 2017-07-31 20:01 UTC
Labels: bug, Cosmetics / Layout / CSS
