### ISSUE TITLE
Add Session - type = Independent Learning not persisting

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#498] opened 2015-04-30 18:22 UTC
If you add a new session, type = Independent Learning then click "Done", the Session Detail screen that slides in currently doesn't reflect the selection of ILM since the user has to then check the ILM checkbox...this is a bug IMO

![screen shot 2015-04-30 at 11 18 02 am](https://cloud.githubusercontent.com/assets/5023894/7419627/28f0b5bc-ef2b-11e4-840b-6e9b428a0449.png)

**Comment by jenzweben** [comment] 2015-04-30 18:33
@saschaben can you confirm that this is a Bug?

**Comment by saschaben** [comment] 2015-04-30 18:36
Not a bug: the session type "Independent Learning" and the Indendent Learning switch for a session are (unfortunately) two different things. You can have non-independent learning "independent learning" and vice versa.

Closing.

**Closed by saschaben** 2015-04-30 18:36 UTC
Labels: bug
