### ISSUE TITLE
Provide user password 'Reset' link for users on form-based authenticated Ilios systems

### ISSUE THREAD

**Issue by thecoolestguy** [ilios/frontend#1613] opened 2016-04-18 21:59 UTC
We need a 'Forgot Password?' password reset service that will allow users to reset their passwords as-needed.  This should include a 'Forgot Password' link on the login page that allows the user to enter their email address that will email them a 'password reset' link that will allow them to change their password and login. (related to #1612)

**Comment by dartajax** [comment] 2020-01-23 22:23
Duplicate of #5037

**Closed by dartajax** 2020-01-23 22:23 UTC
Labels: enhancement
