### ISSUE TITLE
"Safari Web Content Quit Unexpectedly"

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#93] opened 2015-02-11 19:30 UTC
Safari throws a web content crash error frequently during navigation. This does NOT seem to crash the browser itself, and state is maintained, but it is pretty ugly for the user. 

Version 7.1 (9537.85.10.17.1)
OS X Yosemite (10.10.2)

**Comment by jrjohnson** [comment] 2015-02-17 00:46
Please check again after #134 and #136 are merged.  My guess is that this will be fixed.

**Comment by saschaben** [comment] 2015-02-17 00:49
coolio.

**Comment by saschaben** [comment] 2015-02-17 22:27
This occurs when selecting a course from the course list.

**Comment by jrjohnson** [comment] 2015-04-24 04:26
@saschaben - I'm not able to reproduce.  Is this still an issue?

**Closed** 2015-04-24 15:19 UTC
Labels: bug
