### ISSUE TITLE
Learner Groups - subgroup need to change "->" ascii to fa-angle-right in learner-groups.js file

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#638] opened 2015-06-01 20:06 UTC
The title says it all... go to line 143 in learner-groups.js

![screen shot 2015-06-01 at 1 04 27 pm](https://cloud.githubusercontent.com/assets/5023894/7922134/02eb8750-085f-11e5-853a-66a94d6c4e53.png)

**Comment by jrjohnson** [comment] 2015-06-08 02:27
#664 is a duplicate of this, but since the PR is linked to it I'm going to close this one.

**Closed by jrjohnson** 2015-06-08 02:27 UTC
Labels: ready
