### ISSUE TITLE
Provide Error Message in Admin Console when School Permissions are Missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#4652] opened 2019-06-24 22:43 UTC
Currently if you are trying to add a student to a cohort (secondary cohort) but you do not have permission over the learner's primary school.

This happened when a user tried to add a learner to a School of Medicine cohort but the learner was previously in another school (Dentistry or Global Health for example). The user did not have administrative permissions to add the user to School of Medicine because they did not have administrative rights in the Learner's previous school.

We should have a method of failing gracefully and giving them information about why the save could not be performed.

**Comment by saschaben** [comment] 2020-02-27 23:48
duplicate of #3897

**Closed by saschaben** 2020-02-27 23:48 UTC
Labels: enhancement
