### ISSUE TITLE
allow LMs to be search by description as well as title

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#1089] opened 2015-11-10 20:34 UTC
right now, search only returns hits on title. we should return hits on description as well.

**Comment by djvoa12** [comment] 2015-11-13 23:25
@jrjohnson this is a backend search enhancement so punting this off to you.

**Comment by jrjohnson** [comment] 2015-11-13 23:27
Duplicate of https://github.com/ilios/ilios/issues/1057

**Closed by jrjohnson** 2015-11-13 23:27 UTC
Labels: duplicate
