### ISSUE TITLE
Admin Update Not Working Properly

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#2752] opened 2017-03-16 21:26 UTC
Here's what happens (and I tested this on our prod environment as well) ...

Click to update one of the records as indicated below.  

![image](https://cloud.githubusercontent.com/assets/7493331/24019178/358a41e4-0a54-11e7-9db3-126f1edee614.png)

What happens ...

The name disappears as shown below but the record remains.  Clicking `Update Ilios` again will result in a `NULL` error.

![image](https://cloud.githubusercontent.com/assets/7493331/24019243/8848fbe6-0a54-11e7-9ae5-c11aced526aa.png)

**Comment by jrjohnson** [comment] 2017-03-16 21:50
I believe this is a duplicate of #2726

**Closed by jrjohnson** 2017-03-16 21:50 UTC
Labels: bug
