### ISSUE TITLE
Courses and Sessions >> Sessions >> Publish / Unpublish / Mark As Scheduled Ghosting of previous borders

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#407] opened 2015-03-31 23:04 UTC
I was unable to screen shot it unfortunately.  

To reproduce ...

* Open up a Course and Session 
* Click through the changing of the Status between the options available.
* You should see the border of the previously selected status still there like it's been ghosted.

**Comment by jenzweben** [comment] 2015-04-01 19:38
I'm unable to reproduce this @dartajax are you talking about the big publish button?

**Comment by dartajax** [comment] 2015-04-01 20:59
It only happens at the Session level.  The Course level appears to be fine.  Here are my steps ...

* Open up Courses and Sessions 
* Click on "Prologue 2014-15 (IDS 1-1_2014)"
* Select the first session "Anatomy Lab 1 Video ..."
* Change the Session's status from Published to Not Published
* Change the Session's status (state) to Scheduled

At least for a little while you can see the ghost of the previous border on the top edge of the drop-down menu.

**Comment by saschaben** [comment] 2015-04-01 22:19
this may be a windows specific issue - I'm having trouble reproducing on mac (tho I saw it on @dartajax's machine)

**Comment by dartajax** [comment] 2015-04-01 22:37
It seems to only happen on Chrome (not Firefox anyway).  I will show you guys tomorrow.

**Comment by jenzweben** [comment] 2015-04-02 22:27
I googled:  and I think we need to add "transparent" in the class that is controlling the hover state of the publish button (I don't know where that is)
http://stackoverflow.com/questions/6834920/css-border-issues-when-using-hover-on-the-tr

**Comment by jenzweben** [comment] 2015-04-02 22:29
I Googled and I think this might provide the solution but I don't know where in the css to apply it...

http://stackoverflow.com/questions/6834920/css-border-issues-when-using-hover-on-the-tr

**Comment by dartajax** [comment] 2015-05-19 18:08
![stufflikethis](https://cloud.githubusercontent.com/assets/7493331/7710241/57e02696-fe17-11e4-9a9c-7c5f555a4be4.JPG)

**Comment by saschaben** [comment] 2015-06-26 17:17
are we still getting the ghosting at this point, or has this been resolved with code improvements for other issues?

**Closed** 2015-11-04 18:30 UTC
Labels: bug
