### ISSUE TITLE
Delete Functionality Needed in Learning Materials

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#849] opened 2015-10-02 21:59 UTC
Currently, there is no way to delete an uploaded LM.  This is necessary functionality for Course Coordinators as they roll over courses with last year's learning materials that need to be replaced -- removed and then re-uploaded.

Below is a screen shot from one of the mockups that shows an action menu for learning materials.  One of those actions could be "delete" non?

![lmaction1](https://cloud.githubusercontent.com/assets/7493331/10258762/dc5b8640-6915-11e5-8fe8-b134b8c5f9c0.JPG)

Here's what we have currently in 3.0 ... Actions menu is missing.

![lmaction2](https://cloud.githubusercontent.com/assets/7493331/10258780/151c8ede-6916-11e5-8ae1-6478770ff140.JPG)

**Comment by dartajax** [comment] 2015-10-02 22:12
This refers to #450.  I can close this one but can we move #450 up in importance?

**Comment by saschaben** [comment] 2015-10-08 18:17
closing. dupe of #450

**Closed by saschaben** 2015-10-08 18:17 UTC
Labels: ready
