### ISSUE TITLE
Delete Functionality for Course Objective Missing

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#743] opened 2015-06-24 22:22 UTC
There is no way to delete a course objective.

Once it has been added, it can be modified but never deleted.  We should have this functionality present so course objectives can be removed.

**Comment by dartajax** [comment] 2015-06-24 22:25
This refs #450 which I am going through now.

**Comment by saschaben** [comment] 2015-10-08 18:17
closing. dupe of #450

**Closed** 2015-10-08 18:18 UTC
Labels: ready
