### ISSUE TITLE
Calendar View Needed In Session Offerings Section - Same Filters as in 2.4.x

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#1494] opened 2016-03-16 23:18 UTC
It has been pointed out by Administrative users who are involved with attaching Groups to Offerings that it would be very helpful to be able to hover over on the Calendar and see which Groups (if any) are attached to the Calendar Offerings.

If there are multiple groups, in the case of small groups in Week or Month, it could display "Multiple" and then when they click on the small group Offering on the calendar, it opens up into the Day View with the small groups each having their one group attached and this information available on mouse hover over event. 

Is this doable?

**Comment by saschaben** [comment] 2016-03-16 23:33
the ability to see which groups are on the calendar is something we need to reinstate, but I don't think this is the right approach to it. Better to provide a calendar view in the offerings section and return to the v2 options of showing groups, showing free/busy times, showing overlaps, etc.

Showing groups on the main calendar means cluttering an already complex view, as well as playing havoc with potential load times.

**Comment by dartajax** [comment] 2016-03-17 00:25
A lot of people have mentioned how in v2, this used to be visible and reviewable but now it is not.  They miss it.  I can agree with what you are saying about the calendar view complexity; however, I just wanted to point out that we should do something about this to help out with course completeness reviews.  It would be appreciated.

**Comment by saschaben** [comment] 2016-03-17 00:30
@dartajax agreed -- but the functionality you describe was never available in the main calendar of ilios. learner groups have never been listed or displayed there ---- only in the calendar view for offerings management. This is what we need to offer up again, or some form of it.

People also mention frequently how awesome things were when Reagan was president.

**Comment by saschaben** [comment] 2016-04-26 22:45
![freebusy](https://cloud.githubusercontent.com/assets/1753431/14836539/d4985f98-0bc5-11e6-96e2-603559a34523.png)

**Comment by jrjohnson** [comment] 2016-10-11 19:43
Duplicate of #1009

**Closed by jrjohnson** 2016-10-11 19:43 UTC
Labels: enhancement
