### ISSUE TITLE
Dropdown styling 

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#78] opened 2015-02-10 23:09 UTC
I can't figure out how to get this dropdown style http://rsschermer.github.io/ember-rl-dropdown/
to show up on the Courses List page and the Learner Groups page
![screen shot 2015-02-10 at 3 05 02 pm](https://cloud.githubusercontent.com/assets/5023894/6138504/89011092-b136-11e4-9188-4ce07fd15ed3.png)

Here's the css:

color: #333;
background-color: #fff;
border-color: #ccc;
display: inline-block;
padding: 6px 12px;
margin-bottom: 0;
font-size: 14px;
font-weight: 400;
line-height: 1.42857143;
text-align: center;
white-space: nowrap;
vertical-align: middle;
cursor: pointer;
-webkit-user-select: none;
-moz-user-select: none;
-ms-user-select: none;
user-select: none;
background-image: none;
border: 1px solid transparent;
border-radius: 4px;

**Comment by jrjohnson** [comment] 2015-02-10 23:12
You have to wait for #73 to get merged first.  Then re-style as appropriate.

**Comment by jrjohnson** [comment] 2015-02-10 23:14
Closing as a duplicate of #46.

**Closed by jrjohnson** 2015-02-10 23:14 UTC
