### ISSUE TITLE
Still need to fix Filter Tools styling on Course List Page

### ISSUE THREAD

**Issue by jenzweben** [ilios/frontend#158] opened 2015-02-17 23:41 UTC
title says it all - dropdowns should match actions dropdown style.  @jrjohnson please work your magic (or have Jason work his) then assign to me to add css to My Courses checkbox and get the School title at a decent size for the case when the user only has access to one.

**Comment by jrjohnson** [comment] 2015-02-18 04:59
Duplicate of #153

**Closed by jrjohnson** 2015-02-18 04:59 UTC
