### ISSUE TITLE
Competencies Box Displays When No Competencies Have Been Entered

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#441] opened 2015-04-09 21:39 UTC
This occurs upon adding a New Course before a Cohort has been selected.  Under Competencies, there is a shell of a box which would contain the Competencies from that Program Year that have been associated with Course Objectives.  No data = visibility not true.

**Comment by jenzweben** [comment] 2015-04-09 21:47
Duplicate of #393

**Closed by jenzweben** 2015-04-09 21:47 UTC

**Comment by dartajax** [comment] 2015-04-09 21:52
Darn it.  I did a search before entering.  Sorry.
