### ISSUE TITLE
Delete Functionality For Session Missing From Action Menu

### ISSUE THREAD

**Issue by dartajax** [ilios/frontend#742] opened 2015-06-24 16:51 UTC
Currently the only item available under the action menu for a session is Edit.  The Delete action is missing.  Per ticket #450, there should be delete functionality for Session.  I am assuming that is where the Delete action would be performed for a Session.

**Comment by saschaben** [comment] 2015-10-08 18:17
closing. dupe of #450

**Closed by saschaben** 2015-10-08 18:17 UTC
Labels: ready
