### ISSUE TITLE
error adding instructor to instructor group

### ISSUE THREAD

**Issue by saschaben** [ilios/frontend#950] opened 2015-10-27 17:16 UTC
using group 49 (admin/staff), attempt to add Heather Green, throws an error (actually 4) of type 403:

Adapter operation failed

Status Code: 403
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:10:22227)
    at Error.e (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:38:27406)
    at Ye.extend.handleResponse (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29040)
    at c.error (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29961)
    at c (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:11430)
    at Object.d.fireWith (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:12247)
    at r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:4:26252)
    at XMLHttpRequest.t (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:5:408)
Adapter operation failed

Status Code: 403
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:10:22227)
    at Error.e (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:38:27406)
    at Ye.extend.handleResponse (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29040)
    at c.error (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29961)
    at c (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:11430)
    at Object.d.fireWith (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:12247)
    at r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:4:26252)
    at XMLHttpRequest.t (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:5:408)
Adapter operation failed

Status Code: 403
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:10:22227)
    at Error.e (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:38:27406)
    at Ye.extend.handleResponse (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29040)
    at c.error (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29961)
    at c (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:11430)
    at Object.d.fireWith (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:12247)
    at r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:4:26252)
    at XMLHttpRequest.t (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:5:408)
Adapter operation failed

Status Code: 403
Message: The backend responded with an error
Error: Adapter operation failed
    at new Error (native)
    at Error.r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:10:22227)
    at Error.e (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:38:27406)
    at Ye.extend.handleResponse (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29040)
    at c.error (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:39:29961)
    at c (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:11430)
    at Object.d.fireWith (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:3:12247)
    at r (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:4:26252)
    at XMLHttpRequest.t (https://dbsnc1bq6jv0h.cloudfront.net/assets/vendor-c2eaac8e3375e414bf5807aeea364ef0.js:5:408)

**Comment by jrjohnson** [comment] 2015-10-27 17:18
Duplicate of https://github.com/ilios/ilios/issues/1070

**Closed by jrjohnson** 2015-10-27 17:18 UTC
